package com.business.zyvo.model.host.hostdetail

data class HostDetailModel(
    val activities: List<String>,
    val add_on_total: String?,
    val address: String?,
    val amenities: List<String>,
    val amount_of_extension: Any,
    val booking_amount: String?,
    val booking_date: String?,
    val booking_end_time: String?,
    val booking_hour: String?,
    val booking_start_time: String?,
    val booking_status: String?,
    val booking_total_amount: String?,
    val cleaning_fee: String?,
    val distance_miles: String?,
    val guest_avatar: String?,
    val guest_id: Int,
    val guest_name: String?,
    val guest_rating: String?,
    val host_id: Int,
    val host_rules: String,
    val hour_of_extension: Any,
    val images: List<String>,
    val latitude: String?,
    val longitude: String?,
    val parking_rules: String?,
    val property_description: String,
    val property_id: Int,
    val property_title: String,
    val reviews: List<Review>,
    val reviews_total_count: String?,
    val reviews_total_rating: String?,
    val service_fee: String?,
    val tax: String?
)