package com.business.zyvo

import android.icu.util.Calendar
import com.business.zyvo.model.CountryLanguage
import com.google.android.libraries.places.api.Places

class AppConstant {

    companion object {
        val VALID_PHONE: String = "Please enter a valid phone."
        val VALID_EMAIL: String = "Please enter a valid email ID."
        val VALID_PASSWORD: String =
            "Password should be minimum eight characters long and should" + "at least have one numeric, one alphabetic and one special character."
        val WISH: String? = "WISH"
        val NOTIFICATION: String = "Notification"
        val FRIEND_ID: String? = "FRIENDiD"
        val CHANNEL_NAME: String = "Channel_Name"
        val nameHelper: String = "nameHelper"
        val HOST_ID: String? = "HOST_ID"
        val CHAT_TOKEN: String? = "chat_token"
        val PENDING: String = "pending"
        val WAITING_PAYMENT1 = "Awaiting payment"
        val CONFIRMED = "confirmed"
        val CANCEL = "cancelled"
        val FINISHED = "finished"
        val BOOKING_ID: String? = "Booking_id"
        val EXTENSION_ID: String? = "Extension_id"
        val PROPERTY_ID: String? = "property_id"
        val DISCOUNT: String = "Discount"
        val BULK_HOUR: String = "Bulk_Hour"
        val MINIMUM_HOUR: String = "Minimum Hour"
        val WHERE: String = "where"
        val TIME: String = "time"
        val ACTIVITY: String = "activity"
        const val textType: String = "textType"
        var LOGIN_SESSION = "Loggin_setion"
        var Host = "host"
        var Guest = "guest"
        var PANNEL = "Pannel"
        var AuthToken = "AuthToken"
        var Name1 = "FullName"
        val USER_VERIFIED: String? = "user_verified"
        val USER_IMAGE: String? = "user_image"
        val Button = "button"
        val USER_ID: String? = "USER_ID"
        val PRICE: String = "PRICE"
        val type: String? = "type"
        val profileType: String = "street"
        val article: String = "article"
        val Id: String? = "ID"
        val NEEDMORE: String? = "needmore"
        val session: String? = "UserSession"
        val LATITUDE: String = "latitude"
        val LATITUDEGUST: String = "latitudegust"
        val LONGITUDE: String = "longitude"
        val LONGITUDEGUST: String = "longitudegust"
        val NAME: String? = "NAME"
        val MOVE: String = "MOVE"
        val DELETE: String = "delete"
        val ARCHIVED: String = "Archived"
        val Image: String = "image"
        val REPORT: String = "report"
        val BLOCK: String = "block"
        val MUTE: String = "mute"
        val ADD_IMAGE: String = "ADD_IMAGE"
        val EDIT: String = "edit"
        val USER: String = "User"
        val currentYear = Calendar.getInstance().get(Calendar.YEAR)
        val years = (1900..currentYear).toList()
        val FILTERREQUEST: String = "filterRequest"
        val SEARCHFILTERREQUEST: String = "searchfilterRequest"
        val months = listOf(
            "January", "February", "March", "April", "May", "June", "July", "August", "September",
            "October", "November", "December"
        )
        val countriesAndLanguages = listOf(
            CountryLanguage("United States", "English"),
            CountryLanguage("Canada", "English"),
            CountryLanguage("Mexico", "Spanish"),
            CountryLanguage("Brazil", "Portuguese"),
            CountryLanguage("Argentina", "Spanish"),
            CountryLanguage("United Kingdom", "English"),
            CountryLanguage("Germany", "German"),
            CountryLanguage("France", "French"),
            CountryLanguage("Italy", "Italian"),
            CountryLanguage("Spain", "Spanish"),
            CountryLanguage("India", "Hindi"),
            CountryLanguage("China", "Mandarin"),
            CountryLanguage("Japan", "Japanese"),
            CountryLanguage("South Korea", "Korean"),
            CountryLanguage("Russia", "Russian"),
            CountryLanguage("Australia", "English"),
            CountryLanguage("Saudi Arabia", "Arabic"),
            CountryLanguage("Egypt", "Arabic"),
            CountryLanguage("South Africa", "Afrikaans"),
            CountryLanguage("Nigeria", "English"),
            CountryLanguage("Kenya", "Swahili"),
            CountryLanguage("Turkey", "Turkish"),
            CountryLanguage("Iran", "Persian"),
            CountryLanguage("Thailand", "Thai"),
            CountryLanguage("Vietnam", "Vietnamese"),
            CountryLanguage("Pakistan", "Urdu"),
            CountryLanguage("Indonesia", "Indonesian"),
            CountryLanguage("Poland", "Polish"),
            CountryLanguage("Ukraine", "Ukrainian"),
            CountryLanguage("Israel", "Hebrew"),
            CountryLanguage("Chile", "Spanish"),
            CountryLanguage("Colombia", "Spanish"),
            CountryLanguage("Peru", "Spanish"),
            CountryLanguage("Sweden", "Swedish"),
            CountryLanguage("Norway", "Norwegian"),
            CountryLanguage("Denmark", "Danish"),
            CountryLanguage("Finland", "Finnish"),
            CountryLanguage("Netherlands", "Dutch"),
            CountryLanguage("Belgium", "Dutch")
        )

        //All Error Message
        val email = "Email address is required"
        val invalideemail = "Invalid Email Address"
        val password = "Password is required"
        val conPassword = "Confirm Password is required"


        val mobile = "Phone number is required"

        val locationCheck = "Please Add Location Details"
        val languageCheck = "Please Add Language Details"
        val name = "Name is required"
        val firstName = "First name is required"
        val lastName = "Last name is required"
        val otp = "Please enter the OTP"
        val unKnownError = "There was an unknown error. Check your connection, and try again."
        val unknownLocation = "Unknown Location"
        val aboutMe = "About Me is required"
        val details = "Details is required"
        val feedbackAbout = "Please select feedback about"
        val hours = "Hours is required"
        val price = "Price is required"
        val stTime = "Start time is required"
        val edTime = "End time is required"
        val message = "Message is required"
        val emailValid = "Please enter a valid email"
        val description = "Description is required"
        val avabilty = "Please choose an availability window within 24 hours."
        val minimumHour = "Please select at least the minimum required hours to proceed."
        val placeOpenActivity = "placeOpenActivity"
        val property_images = "property_images"
        val latitude = "latitude"
        val longitude = "longitude"
        val property_rating = "property_rating"
        val property_status = "property_status"
        val property_review_count = "property_review_count"
        val distance_miles = "distance_miles"
        val title = "title"


        val cardName = "Card holder name is required"

        val cardNubmer = "Card Number is required"
        val cardValidNubmer = "Please enter a valid card number"
        val cardMonth = "Card month is required"

        val cardYear = "Card year is required"

        val cardCVV = "Card Cvv is required"
        val selectCard = "Please select Card"

        val additional = "Additional Details is required"
        val spinner = "Please select a reason"

        const val firstNameError: String = "First name can't be empty."
        const val lastNameError: String = "Last name can't be empty."
        const val emailError = "Email can't be empty."
        const val phoneError = "phone can't be empty."
        const val dobError: String = "Please select DOB"
        const val selectIdTypeError: String = "Select id type"
        const val pINError: String = "Personal identification number can't be empty."
        const val SNNError: String = "SSN can't be empty."
        const val SNNValidError: String = "Enter Valid SSN."
        const val addressError: String = "Address can't be empty."
        const val countryError: String = "Select country."
        const val stateError: String = "Select State."
        const val cityError: String = "Select City."
        const val postalCodeError: String = "Postal code can't be empty."
        const val bankNameError: String = "Bank Name can't be empty."
        const val cardholderError = "Card Holder Name can't be empty."
        const val accountNumberError = "Account number can't be empty."
        const val cAccountNumberError = "Confirm account number can't be empty."
        const val routingNumberError = "Routing number can't be empty."
        const val proofofbanError = "Please upload proof of bank account."
        const val frontimageError = "Please upload front image."
        const val backimageError = "Please upload back image."
        const val validEmail: String = "Please Enter Valid Email Address"
        const val validPhoneNumber: String = "Please Enter Valid Phone Number"

        //const val Image : String = "image"
        const val propertyList: String = "propertyList"
        const val loginType: String = "LoginType"
        const val passwordMustConsist =
            "The password must consist of at least 8 characters and include at least 1 number, 1 uppercase letter, and 1 special character."

        const val validAvailability: String = "Please enter minimum set hours"
        const val profileUpdateSuccussfully: String = "Your profile has been saved\n successfully"
        const val PROPERTY_DATA = "propertyData"
        const val HOUR = "hour"
        const val PRICE_TEXT = "price"
        const val ST_TIME = "stTime"
        const val ED_TIME = "edTime"
        const val PROPERTY_MILE = "propertyMile"
        const val DATE = "date"
        const val READ_MORE = "Read More"
        const val READ_LESS = "Read Less"
        const val HAVE_DOUBT = "I have a doubt"
        const val AVAILABLE_DAYS = "Available days"
        const val OTHER = "other"
        const val ZYVOOPROJ = "ZYVOOPROJ_"
        const val PLEASE_ENTER_SOMETHING = "Please Enter something"
        const val GUEST_CHANNEL_TYPE = "guest"
        const val USER_IMG = "user_img"
        const val FRIEND_IMG = "friend_img"
        const val FRIEND_NAME = "friend_name"
        const val USER_NAME = "user_name"
        const val SENDER_ID = "sender_id"
        const val MESSAGE = "message"
        const val JANUARY = "January"
        const val FEBRUARY = "February"
        const val MARCH = "March"
        const val APRIL = "April"
        const val MAY = "May"
        const val JUNE = "June"
        const val JULY = "July"
        const val AUGUST = "August"
        const val SEPTEMBER = "September"
        const val OCTOBER = "October"
        const val NOVEMBER = "November"
        const val DECEMBER = "December"

        const val SHOW_LESS = "Show Less"
        const val SHOW_MORE = "Show More"
        const val  BOOKING_ID_TEXT = "bookingId"
        const val DELETE_CARD = "delete"
        const val PRIMARY_CARD = "primary"
        const val KEY_NAME  = "key_name"
        const val ANY = "any"
        const val PRIVATE_ROOM = "private_room"
        const val ENTIRE_HOME= "entire_home"
        const val MINIMUM_PRICE   = "minimum_price"
        const val MAXIMUM_PRICE   = "maximum_price"
        const val STAYS = "Stays"
        const val REQUEST_DATA = "requestData"
        const val EVENT_SPACE = "Event Space"
        const val PHOTO_SHOOT = "Photo shoot"
        const val MEETING = "Meeting"
        const val PARTY = "Party"
        const val POOL = "Pool"
        const val FILM_SHOOT = "Film Shoot" //"Film Shoot"
        const val PERFORMANCE = "Performance"
        const val WORKSHOP = "Workshop"
        const val CORPORATE_EVENT = "Corporate Event"
        const val WEDDING = "Wedding"
        const val RETREAT = "Retreat"
        const val POP_UP = "Pop-up"
        const val NETWORKING = "Networking"
        const val FITNESS_CLASS = "Fitness Class"
        const val AUDIO_RECORDING = "Audio Recording"
        const val DINNER = "Dinner"
        const val PROPERTY_ID_TEXT = "propertyId"
        const val NOT_LOGGING = "NotLogging"
        const val HR_MINIMUM = "hr minimum"
        const val HIGHEST = "Highest"
        const val LOWEST = "Lowest"
        const val RECENT = "Recent"
        const val PROPERTY_SHARE_JPG = "property_share.jpg"
        const val PROPERTY_SHARE = "property_share"
        const val SCFP = "scFp"
        const val BRAND_DOMAIN = "zyvobusiness.onelink.me"
        const val PROPERTY_DETAILS  = "PropertyDetails"
        const val DEEP_LINK = "zyvoo://property"
        const val WEB_LINK = "https://zyvo.tgastaging.com/property"
        const val AF_DP = "af_dp"
        const val AF_WEB_DP = "af_web_dp"
        const val USER_TYPE = "user_type"
        const val LOCATION = "location"
        const val SHARE_VIA = "Share via"
        const val TEXT_PLAIN = "text/plain"
        const val IMAGE_LIST = "image_list"
        const val ZYVO_PROMO_CODE = "Here is Zyvoo Promo Code"
        const val IS_AVAILABLE= "is_available"
        const val START_BOOKING ="Start Booking"
        const val PLACES_INITIALIZE_ID = "AIzaSyC9NuN_f-wESHh3kihTvpbvdrmKlTQurxw" //"AIzaSyC9NuN_f-wESHh3kihTvpbvdrmKlTQurxw"
        const val PM_00_00  = "00:00 PM" //"00:00 PM"
        const val SEARCH_REQUEST_DATA  = "SearchrequestData"   //"SearchrequestData"
        const val ACTIVITY_TEXT= "Activity"
        const val PHOTO_SHOOT_TEXT = "Photo Shoot"
        const val IS_BLOCKED = "is_blocked"
        const val IS_FAVORITE = "is_favorite"
        const val IS_MUTED = "is_muted"
        const val IS_ARCHIVED = "is_archived"
        const val CHOOSE_FROM_GALLERY  = "Choose from gallery" //"Choose from gallery"
        const val TAKE_PHOTO  = "Take a photo"
        const val CANCEL_TEXT  = "Cancel"
        const val SELECT_IMAGE = "Select Image"
        const val FILE_TEXT  = "File"
        const val ONLINE = "Online"
        const val OPEN_PROFILE_FRAGMENT = "OPEN_PROFILE_FRAGMENT"
        const val SHA = "SHA"
        const val GUIDE_ID = "guideId"
        const val ARTICLE  = "Article"
        const val SMOKING_ALLOWED = "Smoking Allowed"
        const val NON_SMOKING_PROPERTY = "Non-Smoking Property"
        const val ADD_WISH  = "Add Wish"
        const val REMOVE_WISH  = "Remove Wish"
        const val ADD_ON_CROSS = "add On Cross"
        const val ADD_ON = "add On"
        const val SET_PRIMARY = "setPrimary"
        const val CARD_NUMBER = "Card Number"
        const val SET_PRIMARY_CARD = "setPrimaryCard"
        const val DELETE_CARD_TEXT  = "deleteCard"
        const val GUIDES = "guides"
        const val APPROVE = "approve"
        const val IM_OVERBOOKED = "I'm overbooked"
        const val MAINTENANCE_DAY = "Maintenance day"
        const val DECLINE = "decline"
        const val CONFIRMED_TEXT = "Confirmed"
        const val AWAITING_PAYMENT_TEXT = "Awaiting Payment"
        const val CANCELLED_TEXT = "Cancelled"
        const val EXTENSION = "extension"
        const val EXAMPLE_DIALOG = "exampleDialog"
        const val FILTER = "filter"
        const val OTHER_ACTIVITIES = "Other Activities"
        const val AMOUNT = "Amount"
        const val STATUS = "Status"
        const val GUEST_NAME = "Guest Name"
        const val DATE_TEXT = "Date"
        const val COMPLETED_TEXT = "COMPLETED"
        const val COMPLETED_SMALL_TEXT = "completed"
        const val STATUS_SMALL_TEXT = "status"
        const val ARTICLE_SMALL_TEXT  = "article"
        const val HOBBIES  = "Hobbies"
        const val ADD_NEW  = "Add New"
        const val LANGUAGE  = "language"
        const val PETS  = "Pets"
        const val WORK  = "work"
        const val WAITING_PAYMENT  = "Waiting Payment"
        const val PENDING_TEXT  = "Pending"
        const val SHARE_THIS_ARTICLE  = "Share This Article:"
        const val SHARE_THIS_GUIDE  = "Share This Guide:"
        const val DATA_SMALL_TEXT  = "data"
        const val USER_ID_SMALL_TEXT  = "user_id"
        const val TOKEN_SMALL_TEXT  = "token"
        const val EMAIL_SMALL_TEXT  = "email"
        const val MOBILE_SMALL_TEXT  = "mobile"
        const val SHOW_DIALOG  = "SHOW_DIALOG"
        const val SIGN_IN_TYPE  = "SIGN_IN_TYPE"
        const val LOGIN_SMALL_TEXT  = "login"
        const val ANDROID_TEXT  = "Android"
        const val REGISTER  = "register"
        const val LOGIN_TYPE  = "LoginType"
        const val LOGIN_TEXT  = "Login"
        const val APPLE_SMALL_TEXT  = "apple"
        const val FACEBOOK_SMALL_TEXT  = "facebook"
        const val LOGIN_PHONE  = "loginPhone"
        const val REGISTER_PHONE  = "RegisterPhone"
        const val REGISTER_EMAIL  = "RegisterEmail"
        const val IS_PROFILE_COMPLETE  = "is_profile_complete"
        const val EMAIL_ADDRESS  = "emailAddress"
        const val ALL_BOOKINGS  = "All Bookings"
        const val FINISHED_TEXT  = "Finished"
        const val HOST_TEXT = "Host"
        const val GUEST_TEXT = "Guest"
        const val PLEASE_SELECT = "Please select"
        const val GUIDES_FOR_GUEST = "Guides for Guests"
        const val GUIDES_FOR_ARTICLES = "Guides for Articles"
        const val GUIDES_TEXT = "Guides"
        const val BOOKINGS_SMALL_TEXT = "bookings"
        const val PROPERTIES_SMALL_TEXT = "properties"
        const val ENTER_PASSWORD = "Enter Password"
    }
}